# Generated by Django 5.1.2 on 2024-12-17 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_remove_book_text_book_author_book_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='description',
        ),
        migrations.RemoveField(
            model_name='book',
            name='published_date',
        ),
    ]
