# Generated by Django 5.1.2 on 2024-12-17 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_remove_book_author_remove_book_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
